export { init } from './core.js'
export { default as SvelteGrab } from './SvelteGrab.svelte'
export { getElementContext, freeze, unfreeze, isFreezeActive } from './primitives.js'
export { registerPlugin, unregisterPlugin, getPlugins } from './plugin-registry.js'
export { defaultCopyPlugin } from './plugins/copy.js'
export { copyHtmlPlugin } from './plugins/copy-html.js'
export { copyStylesPlugin } from './plugins/copy-styles.js'
export { openInEditor } from './open-editor.js'
export { getHistory, clearHistory } from './history.js'
export type { GrabOptions, ElementContext, SourceInfo, Plugin, GrabState } from './types.js'
export type { HistoryItem } from './history.js'
